language: cpp
dist: bionic
os: linux
compiler: clang
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-7
      - llvm-7-dev
env:
  global:
    - CC="/usr/bin/clang-7"
before_install:
  - sudo apt-get install g++-7-multilib gcc-7-multilib
script:
  - git clone --recursive https://github.com/blueway/uWebSockets.js.git
  - cd uWebSockets.js
  - make
  - git checkout binaries
  - cp dist/*.node .
  - git status
  - git pull origin binaries
  - git add uws_linux_ia32_72.node
  - git commit -a -m "[TravisCI] Updated Linux binaries" --allow-empty
  - git push "https://blueway:$SECRET@github.com/blueway/uWebSockets.js" binaries
